---
  - name: Setup Webserver
    hosts: webservers
    become: yes
    tasks:
        - name: Install Apache & PHP Packages
          package:
            name:
                - apache2
                - php
                - libapache2-mod-php 
                - php-curl 
                - php-gd 
                - php-json
                - php-mbstring 
                - php-xml 
                - python-mysqldb         
            state: latest

        - name: Install MariaDB
          package:
              name:
                - mariadb-client
                - mariadb-common
                - mariadb-server
                - php-mysql

        - name: Start mysql service
          service: name=mysql state=started

        - name: Is root password set?
          command: mysql -u root --execute "SELECT NOW()"
          register: is_root_password_set
          ignore_errors: yes

        - name: Generate mysql root password
          shell: tr -d -c "a-zA-Z0-9" < /dev/urandom | head -c 10
          register: mysql_root_password
          when: is_root_password_set.rc == 0

        - name: Set root password
          mysql_user:
            user=root
            password="{{mysql_root_password.stdout}}"
            host=localhost
          when: is_root_password_set.rc == 0

        - name: Inform user of mysql root password
          debug: 
            msg: "Password is {{mysql_root_password.stdout}}"
          when: is_root_password_set.rc == 0
        
